---
title: "Understanding the Model"
output: html_notebook
---


```{r}
library(ggplot2)
library(ggridges)
library(viridis)
raw.data <- get_raw_data()
```

```{r}

model <- raw.data %>% filter(d_type == "model", !condition %in% c("UP.DUR", "DOWN.DUR", "NOCHANGE.DUR"))

trial.dat <- model %>% group_by(experiment, trial) %>% nest()


all.trials <- map(trial.dat$data, function(data) {
  onset.idx <- which(data$condition %in% c("UP", "DOWN", "NOCHANGE"))
  sacc.end.idx <- which(data$condition == "motorEndNum")
  
  sub.trials <- lapply(onset.idx, function(x) {
    sacc.end.pos <- Find(function(y) y > x, sacc.end.idx)
    
    events <- data[x:sacc.end.pos,]
    
    events$type <- as.character(events[1, "condition"])
    
    events %>% group_by(type) %>% nest()
  })
  
  do.call(rbind, sub.trials)
}
)

trial.dat$data <- all.trials$data

trial.dat <- trial.dat %>% unnest(data)

trial.dat$data <- all.trials

summary.stats <- trial.dat %>% mutate(summary.stats = map(data, function(data) {
  N_cancel <- sum(data$condition == "labileInterruptNum")
  duration <- max(data$time) - min(data$time)
  
  data.frame(N_cancel = N_cancel, duration = duration)
})) %>%
  unnest(summary.stats)

ncancel.valid <- summary.stats %>% group_by(N_cancel) %>% summarize(nobs = n()) %>% filter(nobs > 10)

summary.stats <- summary.stats %>% filter(N_cancel %in% ncancel.valid$N_cancel) %>% mutate(duration.1 = duration)

ggplot(summary.stats, aes(x = duration)) + 
  geom_histogram(aes(x = duration, y = ..count../sum(..count..), colour = as.factor(N_cancel), fill = as.factor(N_cancel)), alpha = .2) +
  geom_freqpoly(data = summary.stats %>% select(experiment, type, duration), aes(y = ..count../sum(..count..))) +
  facet_grid(type~experiment)

```

```{r}

model <- raw.data %>% filter(d_type == "model", !condition %in% c("UP.DUR", "DOWN.DUR", "NOCHANGE.DUR"))

trial.dat <- model %>% group_by(experiment, trial) %>% nest()


all.trials <- map(trial.dat$data, function(data) {
  onset.idx <- which(data$condition %in% c("UP", "DOWN"))
  sacc.end.idx <- which(data$condition == "motorEndNum")
  
  sub.trials <- lapply(onset.idx, function(x) {
    sacc.end.pos <- Find(function(y) y > x, sacc.end.idx)
    
    events <- data[x:sacc.end.pos,]
    
    events$type <- as.character(events[1, "condition"])
    
    events %>% group_by(type) %>% nest()
  })
  
  do.call(rbind, sub.trials)
}
)

trial.dat$data <- all.trials$data

trial.dat <- trial.dat %>% unnest(data)

trial.dat$data <- all.trials

summary.stats <- trial.dat %>% mutate(summary.stats = map(data, function(data) {
  N_cancel <- sum(data$condition == "labileInterruptNum")
  duration <- max(data$time) - min(data$time)
  
  data.frame(N_cancel = N_cancel, duration = duration)
})) %>%
  unnest(summary.stats)

ncancel.valid <- summary.stats %>% group_by(N_cancel) %>% summarize(nobs = n()) %>% filter(nobs > 10)

summary.stats <- summary.stats %>% filter(N_cancel %in% ncancel.valid$N_cancel) %>% mutate(duration.1 = duration)

ggplot(summary.stats, aes(x = duration)) + 
  geom_histogram(aes(x = duration, y = ..count../sum(..count..), colour = as.factor(N_cancel), fill = as.factor(N_cancel)), alpha = .2) +
  geom_freqpoly(data = summary.stats %>% select(experiment, type, duration), aes(y = ..count../sum(..count..))) +
  facet_grid(type~experiment)

```
