function f = objVR_exp1_baseline(x)
    WalkRate   = x(2:6);    

    WalkParams_exp1 = x(7:end);
    
    settings_exp1 = lib.rwexperimentset('ExperimentName', 'visionresearch_exp1',...
        'humanDataPath', '_data/h_fixdur_exp1.mat', 'NumberTrials', 50,...
        'NumberStates', round([x(1), repmat(round(x(1)), 1,4)]), 'WalkRate', WalkRate,...
        'ModelParams', WalkParams_exp1,...
        'EventDrivenChangeFcn', @projects.vision_research.VisionResearchParameterAdjustFcn, 'FitnessFcn',...
        @lib.VRMaxLik_baseline, 'NumberSubjects', 1, 'InitializeRandomWalkParameters',...
        @projects.vision_research.VRcreateRandomWalkParams);
    
    f = ucm(settings_exp1);
end