function f = objVR_exp2_baseline(x)
    WalkRate   = x(2:6);    
    
    WalkParams_exp2 = x(7:end);
    
    settings_exp2 = lib.rwexperimentset('ExperimentName', 'visionresearch_exp2',...
        'humanDataPath', '_data/h_fixdur_exp2.mat', 'NumberTrials', 1500,...
        'NumberStates', round([x(1), repmat(round(x(1)), 1,4)]), 'WalkRate', WalkRate,...
        'ModelParams', WalkParams_exp2,...
        'EventDrivenChangeFcn', @projects.vision_research.VisionResearchParameterAdjustFcn, 'FitnessFcn',...
        @lib.VRMaxLik_baseline, 'NumberSubjects', 1, 'InitializeRandomWalkParameters',...
        @projects.vision_research.VRcreateRandomWalkParams);
    
    f = ucm(settings_exp2);
end