function f = objVR_exp1_adaptation(x)    
    WalkRate   = x(2:6);
    
    WalkParams_exp1 = x(7:end);
    %WalkParams_exp1 = [x((1 + n_rate_params + n_adj_params + 1):(end - n_stage_params)), x(end-1:end)];    
    nWalk = x(1);
    if mod(x(1),1) ~= 0
        
        x(1) = floor(nWalk);        
        settings_exp1_low = lib.rwexperimentset('ExperimentName', 'visionresearch',...
            'humanDataPath', '_data/h_fixdur_exp1.mat', 'NumberTrials', 1500,...
            'NumberStates', round([x(1), repmat(round(x(1)), 1,4)]), 'WalkRate', WalkRate,...
            'ModelParams', WalkParams_exp1,...
            'EventDrivenChangeFcn', @projects.vision_research.VisionResearchParameterAdjustFcn, 'FitnessFcn',...
            @lib.VRMaxLik_adaptation, 'NumberSubjects', 1, 'InitializeRandomWalkParameters',...
            @projects.vision_research.VRcreateRandomWalkParams);

        x(1) = ceil(nWalk);
        settings_exp1_high = lib.rwexperimentset('ExperimentName', 'visionresearch',...
            'humanDataPath', '_data/h_fixdur_exp1.mat', 'NumberTrials', 1500,...
            'NumberStates', round([x(1), repmat(round(x(1)), 1,4)]), 'WalkRate', WalkRate,...
            'ModelParams', WalkParams_exp1,...
            'EventDrivenChangeFcn', @projects.vision_research.VisionResearchParameterAdjustFcn, 'FitnessFcn',...
            @lib.VRMaxLik_adaptation, 'NumberSubjects', 1, 'InitializeRandomWalkParameters',...
            @projects.vision_research.VRcreateRandomWalkParams);

        f_low  = ucm(settings_exp1_low);
        f_high = ucm(settings_exp1_high);    
        f      = mean([f_low, f_high]);
    else      
        settings_exp1 = lib.rwexperimentset('ExperimentName', 'visionresearch',...
            'humanDataPath', '_data/h_fixdur_exp1.mat', 'NumberTrials', 1500,...
            'NumberStates', round([x(1), repmat(round(x(1)), 1,4)]), 'WalkRate', WalkRate,...
            'ModelParams', WalkParams_exp1,...
            'EventDrivenChangeFcn', @projects.vision_research.VisionResearchParameterAdjustFcn, 'FitnessFcn',...
            @lib.VRMaxLik_adaptation, 'NumberSubjects', 1, 'InitializeRandomWalkParameters',...
            @projects.vision_research.VRcreateRandomWalkParams);
        f = ucm(settings_exp1);        
    end
end