x = [7.5068   20.0000  237.9460  160.9283  107.6758   30.0000   20.0000    1.0000    1.0000    1.0000    1.0000    1.0000    1.0000];

n_rate_params  = 5;
n_adj_params   = 4;
n_stage_params = 2;

WalkRate   = x(3:7);    

WalkParams_exp1 = [x(8:11), x(end-1:end)];

%WalkParams_exp2 = [x((1 + n_rate_params + n_adj_params + 1):(end - n_stage_params)), x(end-1:end)];

settings_exp1 = lib.rwexperimentset('ExperimentName', 'visionresearch',...
    'humanDataPath', '_data/h_fixdur_exp1.mat', 'NumberTrials', 500,...
    'NumberStates', round([x(1), repmat(round(x(2)), 1,4)]), 'WalkRate', WalkRate,...
    'ModelParams', WalkParams_exp1,...
    'EventDrivenChangeFcn', @projects.vision_research.VisionResearchParameterAdjustFcn, 'FitnessFcn',...
    @lib.VRMaxLik, 'NumberSubjects', 1, 'InitializeRandomWalkParameters',...
    @projects.vision_research.VRcreateRandomWalkParams, 'PlotFcn', @vis.plot_data);

%     settings_exp2 = lib.rwexperimentset('ExperimentName', 'visionresearch',...
%         'humanDataPath', '_data/h_fixdur_exp2.mat', 'NumberTrials', 150,...
%         'NumberStates', repmat(round(x(1)), 1,5), 'WalkRate', WalkRate,...
%         'ModelParams', WalkParams_exp2,...
%         'EventDrivenChangeFcn', @projects.vision_research.VisionResearchParameterAdjustFcn, 'FitnessFcn',...
%         @lib.VRMaxLik, 'NumberSubjects', 1, 'InitializeRandomWalkParameters',...
%         @projects.vision_research.VRcreateRandomWalkParams);

f_exp1 = ucm(settings_exp1);